# Replaced with flameshot and helper script
- name: Removing Unneeded package - APT
  apt:
    pkg:
      - gnome-screenshot
      - firefox
    state: absent

- name: Installing Services - APT
  apt:
    pkg:
      - snapd
      - openssh-server
      - profile-sync-daemon
    state: present

- name: Installing System Packages - APT
  apt:
    pkg:
      - ubuntu-restricted-extras
      - gnome-firmware
      - python3-pip
      - snapd-xdg-open
      - gnupg-agent
      - pulseaudio
      - pavucontrol
      - preload
      - dex
      - aptitude
    state: present

- name: Installing 3rd Party (PPA) User Applications - APT
  apt:
    pkg:
      - nordvpn
      - brave-browser-nightly
      - tailscale
      - peek
      - pop-fonts
      - pop-sound-theme
      - pop-icon-theme

    state: present

- name: Installing Fonts - APT
  apt:
    pkg:
      - ttf-mscorefonts-installer
      - fonts-emojione
    state: present

- name: Installing Logitech Support - APT
  apt:
    pkg:
      - solaar
      - piper
      - v4l-utils
    state: present

- name: Installing User Applications - APT
  apt:
    pkg:
      - ncdu
      - whois
      - tmux
      - lftp
      - htop
      - celluloid
      - xclip
      - flameshot
      - gnome-calculator
      - gnome-disk-utility
      - dlocate
      - ppa-purge
      - seafile-cli
      - dialog
      - encfs
      - gocryptfs
      - bat
      - seahorse
      - sirikali
    state: present

- name: Installing Developer Tools - APT
  apt:
    pkg:
      - git
      - jq
      - dh-make
      - debconf-utils
      - debhelper
      - ubuntu-dev-tools
      - piuparts
      - schroot
      - sbuild
      - uncrustify
      - devscripts
      - software-properties-gtk
      - pylint
      - gtk-3-examples
      - libgtk-3-0
    state: present

- name: Installing i3rocks Modules - APT
  apt:
    pkg:
      - i3xrocks-media-player
      - i3xrocks-volume
    state: present

- name: Installing i3rocks Modules (Laptop) - APT
  tags:
  - laptop
  apt:
    pkg:
      - i3xrocks-wifi
      - i3xrocks-battery
      - i3xrocks-temp
    state: present

- name: Removing i3rocks Modules (Laptop) - APT
  tags:
  - laptop
  apt:
    pkg:
      - i3xrocks-net-traffic
    state: absent

- name: Installing Regolith Looks - APT
  apt:
    pkg:
      - regolith-look-nord
    state: present

- name: Installing Vala and Dependencies
  tags:
  - install-vala
  apt:
    pkg:
      # "uncrustify" is used but installed in the main installation
      - valac
      - valadoc
      - meson

- name: Installing Xmind - APT
  apt:
    deb: https://www.xmind.net/xmind/downloads/XMind-2020-for-Linux-amd-64bit-{{ xmind_version }}.deb
